In [4]:
import pandas as pd
import datetime as dt

In [8]:
monthly_revenue = pd.read_csv('../data/monthly_revenue.csv')
monthly_revenue.columns

Index(['month', 'total_active_customers', 'new_customers', 'churned_customers',
       'monthly_churn_rate_pct', 'total_mrr', 'avg_revenue_per_customer',
       'customer_acquisition_cost'],
      dtype='str')

In [9]:
monthly_revenue.head()

,month,total_active_customers,new_customers,churned_customers,monthly_churn_rate_pct,total_mrr,avg_revenue_per_customer,customer_acquisition_cost
0,2022-01,0,5,0,0.00,0.00,0.00,164.92
1,2022-02,5,10,1,20.00,7333.07,1466.61,189.21
2,2022-03,14,13,0,0.00,12301.16,878.65,139.49
3,2022-04,28,11,3,10.71,24798.76,885.67,259.09
4,2022-05,35,11,1,2.86,29091.88,831.20,152.96

In [10]:
monthly_revenue.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   total_active_customers     48 non-null     int64
 2   new_customers              48 non-null     int64
 3   churned_customers          48 non-null     int64
 4   monthly_churn_rate_pct     48 non-null     float64
 5   total_mrr                  48 non-null     float64
 6   avg_revenue_per_customer   48 non-null     float64
 7   customer_acquisition_cost  48 non-null     float64
dtypes: float64(4), int64(3), str(1)
memory usage: 3.1 KB

In [12]:
subscriptions = pd.read_csv('../data/subscriptions.csv')
subscriptions.head()

,customer_id,plan,billing_cycle,industry,company_size,seats,monthly_revenue,acquisition_channel,region,signup_date,churned,churn_date,churn_reason,support_tickets_12mo,nps_score,feature_usage_pct,upgraded
0,CUST-0001,Professional,Monthly,Retail,51-200,64,825.55,Organic Search,North America,2022-06-27,Yes,2024-03-05,Price Too High,13,3,15,No
1,CUST-0002,Professional,Annual,Retail,51-200,35,409.62,Direct Sales,North America,2023-03-19,No,NaN,NaN,1,3,52,Yes
2,CUST-0003,Starter,Annual,Finance,500+,266,1004.49,Partner,North America,2024-10-19,Yes,2025-04-13,Price Too High,10,4,31,No
3,CUST-0004,Business,Annual,Real Estate,11-50,34,1006.44,Partner,Europe,2023-01-07,No,NaN,NaN,3,7,58,No
4,CUST-0005,Starter,Annual,Manufacturing,51-200,48,198.43,Direct Sales,North America,2025-09-23,No,NaN,NaN,3,7,59,No

In [13]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           600 non-null    str
 1   plan                  600 non-null    str
 2   billing_cycle         600 non-null    str
 3   industry              600 non-null    str
 4   company_size          600 non-null    str
 5   seats                 600 non-null    int64
 6   monthly_revenue       600 non-null    float64
 7   acquisition_channel   600 non-null    str
 8   region                600 non-null    str
 9   signup_date           600 non-null    str
 10  churned               600 non-null    str
 11  churn_date            313 non-null    str
 12  churn_reason          313 non-null    str
 13  support_tickets_12mo  600 non-null    int64
 14  nps_score             600 non-null    int64
 15  feature_usage_pct     600 non-null    int64
 16  upgraded              600 non-null    str
dtypes: float64(1), int64(4), str(12)
memory usage: 79.8 KB

In [14]:
subscriptions['company_size'].unique()

<StringArray>
['51-200', '500+', '11-50', '1-10', '201-500']
Length: 5, dtype: str

In [15]:
subscriptions['billing_cycle'].unique()

<StringArray>
['Monthly', 'Annual']
Length: 2, dtype: str

In [17]:
subscriptions.plan.unique()

<StringArray>
['Professional', 'Starter', 'Business', 'Enterprise']
Length: 4, dtype: str

CLEANING

In [19]:
monthly_revenue['date'] = pd.to_datetime(monthly_revenue['month'] +'-1' , errors='coerce')

In [20]:
monthly_revenue.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   total_active_customers     48 non-null     int64
 2   new_customers              48 non-null     int64
 3   churned_customers          48 non-null     int64
 4   monthly_churn_rate_pct     48 non-null     float64
 5   total_mrr                  48 non-null     float64
 6   avg_revenue_per_customer   48 non-null     float64
 7   customer_acquisition_cost  48 non-null     float64
 8   date                       48 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(3), str(1)
memory usage: 3.5 KB

In [21]:
monthly_revenue.head()

,month,total_active_customers,new_customers,churned_customers,monthly_churn_rate_pct,total_mrr,avg_revenue_per_customer,customer_acquisition_cost,date
0,2022-01,0,5,0,0.00,0.00,0.00,164.92,2022-01-01
1,2022-02,5,10,1,20.00,7333.07,1466.61,189.21,2022-02-01
2,2022-03,14,13,0,0.00,12301.16,878.65,139.49,2022-03-01
3,2022-04,28,11,3,10.71,24798.76,885.67,259.09,2022-04-01
4,2022-05,35,11,1,2.86,29091.88,831.20,152.96,2022-05-01

In [22]:
subscriptions['churned']=(subscriptions['churned']=='Yes').astype(int)

In [23]:
subscriptions['upgraded'] = (subscriptions['upgraded'] == 'Yes').astype(int)

In [24]:
subscriptions['churn_date'] = pd.to_datetime(subscriptions['churn_date'], errors='coerce')

In [25]:
subscriptions['signup_date'] = pd.to_datetime(subscriptions['signup_date'], errors='coerce')

In [26]:
print(subscriptions.signup_date.max())
print(subscriptions.signup_date.min())

2025-12-31 00:00:00
2022-01-06 00:00:00

In [27]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           600 non-null    str
 1   plan                  600 non-null    str
 2   billing_cycle         600 non-null    str
 3   industry              600 non-null    str
 4   company_size          600 non-null    str
 5   seats                 600 non-null    int64
 6   monthly_revenue       600 non-null    float64
 7   acquisition_channel   600 non-null    str
 8   region                600 non-null    str
 9   signup_date           600 non-null    datetime64[us]
 10  churned               600 non-null    int64
 11  churn_date            313 non-null    datetime64[us]
 12  churn_reason          313 non-null    str
 13  support_tickets_12mo  600 non-null    int64
 14  nps_score             600 non-null    int64
 15  feature_usage_pct     600 non-null    int64
 16  upgraded              600 non-null    int64
dtypes: datetime64[us](2), float64(1), int64(6), str(8)
memory usage: 79.8 KB

Validations

In [30]:
print(f"\nDate range:{subscriptions.signup_date.min()} to {subscriptions.signup_date.max()}")
print(f"total customers: {subscriptions['customer_id'].nunique()}")
print(f"Total churn rate: {subscriptions['churned'].mean():.2%}")
print(f"Churned reasons: {subscriptions['churn_reason'].value_counts()}")

print(f"\nChurn by plan:")
for plan, rate in subscriptions.groupby('plan')['churned'].mean().items(): #Convert the result to a list of (plan, rate) pairs.
    print(f" {plan}: {rate:.2%}")

Date range:2022-01-06 00:00:00 to 2025-12-31 00:00:00
total customers: 600
Total churn rate: 52.17%
Churned reasons: churn_reason
Budget Cuts            53
Price Too High         51
Company Closed         48
Poor Support           42
No Longer Needed       41
Missing Features       40
Switched Competitor    38
Name: count, dtype: int64

Churn by plan:
 Business: 41.25%
 Enterprise: 22.00%
 Professional: 47.98%
 Starter: 70.51%

In [31]:
# Business logic validation
assert subscriptions['monthly_revenue'].min() >= 0, "Revenue cannot be negative"
assert subscriptions['churned'].max() <= 1, "churned should be 0 or 1"
assert subscriptions['nps_score'].max() <= 10, "NPS should be 0-10"
assert subscriptions['feature_usage_pct'].max() <= 100, "Feature usage should be 0-100%"

In [32]:
print(f" ✓ All business logic constraints met")

 ✓ All business logic constraints met

In [33]:
monthly_revenue_cleaned = monthly_revenue.copy()
subscriptions_cleaned = subscriptions.copy()

monthly_revenue_cleaned.to_csv('../data/processed/monthly_revenue_cleaned.csv', index=False)
subscriptions_cleaned.to_csv('../data/processed/subscriptions_cleaned.csv', index=False)